name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Pour la publication de confiance
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utilise la dernière version

      - name: Set up Python
        uses: actions/setup-python@v4  # Dernière version de l'action Python
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # Publier sur PyPI
